version: "3"

services:
  web:
    image: node-app
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
    ports:
     - "5000:5000"
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
     - web
    depends_on:
     - mongodb
  
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - db-mongo:/data/db
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
    networks:
      - web

  mongo-express:
    image: mongo-express
    restart: always
#    links:
#      - mongodb:mongo
#    depends_on:
#      - mongodb
    networks:
      - web
    ports:
      - 9081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
 
  visualizer:
    image: dockersamples/visualizer
    ports:
      - "9080:8080"
    stop_grace_period: 1m30s
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      placement:
        constraints: [node.role == manager]

  
networks:
  web:

volumes:
  db-mongo:
