version: "2"

services:
  web:
    build: .
    ports:
     - "5000:5000"
    networks:
     - web
  
  mongodb:
    image: mongo:latest
    volumes:
     - ~/Docker/mongo:/data/db
    networks:
     - web
  
networks:
  web: